require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/MethodLength:
  CountAsOne:
    - heredoc

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/html2rss/generator_spec.rb

RSpec/ExampleLength:
  Max: 6

RSpec/ImplicitSubject:
  Enabled: false

Layout/ClassStructure:
  Enabled: true
